### ISSUE TITLE
Don't require RegistrationActions if the feature is disabled

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-auth-shared#33]
#### Describe the desired behavior
Users shouldn't need to supply the RegistrationUIActions if they have disabled the registration capabilities

#### Describe the current behavior
This prop is required even if the registration capabilities are disabled.

#### Is this request related to a current issue?
This was requested by the Red/Green seed UI team.

#### Additional Context

This could be more involved than it seems...it would require adding a bunch of conditional logic throughout since functions are no longer guaranteed to exist, plus probably some sort of type unions to only make it required when the other props are true.

**Comment by huayunh** [comment]
Will transfer to JIRA

**Comment by huayunh** [comment]
PXBLUE-2159
