### ISSUE TITLE
Remove title prop from AuthUIContextProvider code and API documentation

### ISSUE THREAD

**Issue by daileytj** [pxblue/react-auth-shared#6]
#### Describe the desired behavior
Remove title prop from AuthUIContextProvider code and API

#### Describe the current behavior
There is a "title" prop in the AuthUiContextProvider and our documentation that doesn't actually do anything.
Remove this prop and references to it in the documentation to avoid potential confusion.

**Comment by joebochill** [comment]
This was removed in #12
